spring:
  application:
    name: currency-exchange

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8100

management:
  tracing:
    sampling:
      probability: 1.0 # Tracing 100% of the requests that are coming to currency-conversion-service

logging:
  pattern:
    level:%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
